- hosts: all
  become: yes
  vars:
    k8s_user: devops

  tasks:
    - name: "Create the {{ k8s_user }} user"
      user: name="{{ k8s_user }}" append=yes state=present createhome=yes shell=/bin/bash

    - name: "Allow {{ k8s_user }} to have passwordless sudo"
      lineinfile:
        dest: /etc/sudoers
        line: "{{ k8s_user }} ALL=(ALL) NOPASSWD: ALL"
        validate: 'visudo -cf %s'

    - name: "Set up authorized keys for the {{ k8s_user }} user"
      authorized_key: user="{{ k8s_user }}" key="{{ item }}"
      with_file:
        - ~/.ssh/id_rsa.pub